# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35377d7b680576f368d67b7d41f67bfce91b55b6d805b0cb3833f7561349d5b1d63fa900e62d5e4d8dcae773ff70194b462fe955f6bd2b68b83428c2221b5970

test:
  secret_key_base: 87193e9177ce600d5ab09e6ee156d93d3749741e3596edc43f0cb2b7713ccd303c16b927795a27b75893e3ecbb238882692659c1e8fb6921328c393509012a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
